name: "Drawio exporter"
description: "Exports dot drawio file to specified format"
inputs:
  input-filename:
    description: "Full path to input file"
    required: true
  format:
    description: 'Which format to export file to. Possible export formats are pdf, png, jpg, svg, and xml) (default: "svg")'
    required: false
    default: "svg"
outputs:
  output-filename:
    description: "Output filename path"
    value: ${{ steps.export.outputs.output-filename }}
runs:
  using: "composite"
  steps:
    - name: Export drawio file
      id: export
      shell: bash
      run: |
        output=$(docker run --rm -v $PWD:/data rlespinasse/drawio-desktop-headless:v1.46.0 -f "${{ inputs.format }}" -x "/data/${{ inputs.input-filename }}" 2>&1)
        echo "Docker output: $output"

        output_file=$(echo "$output" | grep -- '-> /data' | awk -F'-> /data/' '{print $2}' | tail -1)

        # Set the output
        echo "output-filename=$output_file" >> $GITHUB_OUTPUT
        echo "Generated file: $output_file"
