on: [push]

jobs:
  drawio_exporter_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Export to svg
        id: export
        uses: ./
        with:
          input-filename: 'test.drawio'
