on: [push]

jobs:
  drawio_exporter_job:
    runs-on: ubuntu-latest
    name: A job to test if works
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export to svg
        id: export
        uses: ./
        with:
          input-filename: "test.drawio"
      - name: Print output filename
        run: echo "Output file is ${{ steps.export.outputs.output-filename }}"

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: exported-file
          path: ${{ steps.export.outputs.output-filename }}
          overwrite: true
